config/routes.rb
Rails.application.routes.draw do

  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users 
         
 resources :profiles      
    

 get 'profiles/subregion_options' => 'profiles#subregion_options'
  get 'surveys/subregion_options' => 'surveys#subregion_options'
  get 'surveys/review' => "surveys#review"
  	resources :surveys do
       member do
        get :finish
        put :finish
        get :approve
        put :approve
        post :approve        
        get :new_profile
        get :edit_profile
        patch :update_profile

      post :create_profile      
      get :new_response
      post :create_response
    end
        end
  root 'surveys#index'








  end

app/models/survey.rb
class Survey < ApplicationRecord
	 #attr_accessor :name, :questions_attributes
	has_many :questions, dependent: :destroy
	has_many :responses, dependent: :destroy
	has_one :profile, as: :profilable, dependent: :destroy
	belongs_to :user
	accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :profile, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :responses, reject_if: :all_blank, allow_destroy: true
	validates :name, presence: true
	validates :plimit, presence: true

	validate :survey_reward
	#before_update :survey_reward, on:[:create, :update]
	#before_create :survey_reward, on:[:create, :update]




private 

def survey_reward
	questions = self.questions

	user = User.find(self.user_id)
	if user.budget.fbcbudget < ((self.tempreward - self.reward) * self.plimit) or self.plimit < 1000 
	errors.add(:tempreward, 'Your Budget or Part. limit(min:1000) is not enough to submit')
	
	elsif tempreward < 1
	errors.add(:tempreward, 'You have to define Reward per user(min = 1.0 FBC)')
	
	elsif questions.blank?
	errors.add(:question, 'Please put question under survey less one')
	
	end
	
		questions.each do |q|
		if q.options.nil? or q.options.size < 2
			errors.add(:option,'Please put options under questions more than one')
		

		end
		end
		
end







	









end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :check_responsed, only:[:new_response, :create_response]
  before_action :if_profile_nil, only: [:show, :create_response, :new_response]
  before_action :check_user_profile, except: :subregion_options
  before_action :check_admin, only: [:finish, :approve, :review]
  before_action :check_show, only:[:show, :edit]
  before_action :check_customer, only: [:create, :new, :edit]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.order('created_at DESC').where(approved: true, finished: false)
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show 

   @country = Carmen::Country.coded(@survey.profile.country_code)
    @subregions = @country.subregions
    @state = @subregions.coded(@survey.profile.state_code)
  
  end

  # GET /surveys/new
   def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json 
      end 
end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = current_user.surveys.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        @survey.update_attribute(:approved, false)
        @survey.update_attribute(:reviewed, false)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html {  render :edit  }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



def new_response
@survey = Survey.find(params[:id])
@response = @survey.responses.build

    # now, the tricky part, you have to build the Answer objects so you can use the nested form later
    @survey.questions.each do |q|
      @response.answers.build question: q
    end
  end



def create_response
  @survey = Survey.find(params[:id])
  @response = @survey.responses.build(response_params)
  @response.user = current_user
  respond_to do |format|
          if @response.save
          format.html { redirect_to @survey, notice: 'Response was successfully submitted.' }
          format.json { render :show, status: :created, location: @survey }

      else
        format.html { redirect_to new_response_survey_path, alert: 'You must response to all questions.' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
        end
    end  
end


def approve
  
   set_survey
   check_balance
      @survey.user.budget.decrement!(:fbcbudget,  (@survey.tempreward - @survey.reward) * @survey.plimit)
      @survey.increment!(:totalr, (@survey.tempreward - @survey.reward) * @survey.plimit)
      @survey.increment!(:reward, @survey.tempreward - @survey.reward)
      @survey.update_attribute(:approved, true)
      @survey.update_attribute(:reviewed, true)

    
    redirect_to surveys_review_path



end


def review
if current_user.admin?
        @surveys = Survey.order('created_at ASC').where(reviewed: false, approved: false)
        @unf_surveys = Survey.order('created_at ASC').where(approved: true, finished: false)
      else        
       redirect_to root_path, alert: 'You dont have permission to review'
    end
end




  def finish
    
      set_survey
      if @survey.finished?
        redirect_to surveys_review_path, alert: 'Sorry... Survey already Finished.'    
      else      
      @survey.update_attribute(:finished, true)
      @survey.responses.each do |response| 
      response.user.budget.increment!(:fbcbudget,  @survey.reward)
      @survey.decrement!(:totalr,  @survey.reward)
      end
      @survey.user.budget.increment!(:fbcbudget,  @survey.totalr)
      redirect_to surveys_review_path, notice: 'Survey Successfully Finished.'
      end


  end


  def new_profile
@survey = Survey.find(params[:id])
@profile = @survey.build_profile

end


def edit_profile
@survey = Survey.find(params[:id])
@profile = @survey.profile
end

def update_profile
  @survey = Survey.find(params[:id])
  @profile = @survey.profile
respond_to do |format|
      if @survey.profile.update(profile_params)
        format.html { redirect_to @survey, notice: "Survey's Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html {  redirect_to edit_profile_survey_url, alert: 'Survey Profile creating failed. please make sure about all fields.'  }
        format.json { render json: @survey.proile.errors, status: :unprocessable_entity }
      end
    end

end



def create_profile
 @survey = Survey.find(params[:id])
  @profile = @survey.build_profile(profile_params)

  respond_to do |format|    
          if @profile.save
          format.html { redirect_to @survey, notice: 'Survey Profile was successfully submitted.' }
          format.json { render :show, status: :created, location: @survey }

      else

        format.html { redirect_to new_profile_survey_url, alert: 'Survey Profile creating failed. please make sure about all fields.' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }


        end
    end  
  
end








def subregion_options
  render partial: 'subregion_select'
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :tempreward, :reward, :plimit, questions_attributes:[:id, :title, :qtype, :survey_id, :_destroy, options_attributes:[:id, :otext, :question_id,:_destroy]])
    end

def response_params
  params.require(:response).permit(answers_attributes:[:question_id, :option_id])  
end

def profile_params
   params.require(:profile).permit(:country_code, :state_code, :gender, :lang, :max_age, :min_age, :birthday)
  
end

def check_responsed
set_survey
  
    if @survey.responses.exists?(user_id: current_user.id)
    redirect_to root_path, alert: 'You have already answered the survey'
    end
  
end




def decrement!(attribute, by = 1)
  decrement(attribute, by).update_attribute(attribute, self[attribute])
end

def increment!(attribute, by = 1)
  increment(attribute, by).update_attribute(attribute, self[attribute])
end

def check_balance
  if current_user.budget.fbcbudget < (@survey.tempreward - @survey.reward) or @current_user.budget.fbcbudget < 1000
    redirect_to root_path, alert: 'User budget is not enough'
  end
  
end


def if_profile_nil
  @survey = Survey.find(params[:id])
    if current_user.id == @survey.user_id and @survey.profile.nil?
      flash[:alert] = "You have to create profile before sharing the survey"
      redirect_to new_profile_survey_path
    elsif @survey.profile.nil?
      flash[:alert] = "This Survey has no profile yet."
      redirect_to root_path
    end
end

  def check_user_profile

      if current_user.profile.nil?
        flash[:alert] = "You have to create profile before any activity"
      redirect_to new_profile_path
          end      
      
    end


def check_admin
redirect_to root_path, alert: 'Oops...You dont have permission for this action'  unless current_user.admin? or current_user.role == "Moderator"
  
 
end

def check_show

if current_user.role == "Moderator" or current_user.admin? or current_user == @survey.user

else
   redirect_to root_path, alert: 'Only Creator can show the results.(Customer Privacy)'  
end
  
end


def check_customer

  unless current_user.role == "Moderator" or current_user.admin? or current_user.role == "Customer"
   redirect_to root_path, alert: 'Only Allowed Customers can create Survey'
  
  end
end




end

app/views/surveys/_form.html.slim
- if @survey.errors.any?   
  ul
    - @survey.errors.full_messages.each do |msg| 
      li = msg
#newsurvey class= "form-group" 
   = form_for @survey do |f|    
     #numbers class="row"
      #perresponse class="col"
         span data-toggle="tooltip" data-placement="top" title="(How much FBC you will pay per pesponser?)"
            = f.label "Survey Reward (?)"
         = f.number_field :tempreward, value: number_to_currency(f.object.tempreward.to_f, precision: 3, scale: 15, delimiter: '', unit: ''), step: :any    
      #perresponse class="col"             
         span data-toggle="tooltip" data-placement="top" title="(How much participant can response?)"
            = f.label "Participants limit(?):" 
         = f.number_field :plimit
      = f.label "Note: Reward per Participant * Participant limit = Total will have been decreased from your budget when approved by management)", color: "red"
     br
     = f.label "Survey Name:"
     br
     = f.text_field :name, placeholder:"Survey Name", class:"form-control"
     hr
     #questions    
      h3 questions     
      = f.fields_for :questions do |question|        
        = render 'question_fields', f: question
      .links
        = link_to_add_association 'add question', f, :questions, class:"btn btn-success btn-sm"


       

     hr   
     = f.submit class:"btn btn-primary"

app/views/surveys/_head_file.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">FEEDBACK CHAIN</a>
    <form class="form-inline">
    <% if user_signed_in? %>
 <a role="button" class="btn btn-outline-primary"> <%= "You have: #{number_to_currency(current_user.budget.fbcbudget.to_f, unit: "FBC ") unless nil?}   " %> </a>
   <a role="button" > <%= link_to 'Create Survey', new_survey_path, class: "btn btn-outline-info" %> 
   </a>
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Account
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <% if current_user.admin? %>  
    <a class="dropdown-item" href="/surveys/review">Review Surveys</a>        
    <a class="dropdown-item" href="/admin"> Admin Panel </a>
       <% end %>
    <a class="dropdown-item" href="/users/edit">Edit Account</a>
    <a><%= link_to "Profile", current_user.profile, class: "dropdown-item"  %></a>
    <a><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"  %></a>
  </div>
  



       
        

    <% else %>
       <a role="button"> <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary"  %> </a>
    <a role="button"> <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary"  %> </a>
    <% end %>
    
    
  </form>
</nav>

app/views/surveys/_option_fields.html.slim
 .nested-fields  
 	= f.text_field :otext, placeholder:"Option Title", class:"form-control"  	 
  	= link_to_remove_association "Remove Option X", f, class:"btn btn-danger btn-sm"

app/views/surveys/_profile_fields.html.slim
.nested-fields
  = f.label "Country"
  br
  = f.country_select :country_code, priority: %w(US CA), prompt: 'Please select a country'
  br
  #field
  	= f.label "City"
  	br
  	= render 'subregion_select', locals: {parent_region: f.object.country_code}
  br
  = f.label "Gender"
  br
  = f.select :gender, Profile.genders.keys.to_a
  br
  = f.label "Your Language"
  br
  = f.select :lang, Profile.langs.keys.to_a
  br
  = f.label "Birthdate"
  br
  = f.date_field :birthday
  
 

app/views/surveys/_subregion_select.html.slim
#profile_state_code_wrapper
  - parent_region ||= params[:parent_region]
  - country = Carmen::Country.coded(parent_region)

  - if country.nil? 
    em Please select a country above
  - elsif country.subregions? 
    = subregion_select(:profile, :state_code, parent_region) 
  - else 
    = text_field(:profile, :state_code) 
  

app/views/surveys/_unfinished_surveys.html.slim
#container
    - @unf_surveys.each do |survey|
      #survey class="row"
            #title class="col"       
              h6 style="display: inline-block" =link_to "#{survey.name} ( T.Reward:#{survey.tempreward}), A.Reward:#{survey.reward}, Total R:#{survey.totalr}", new_response_survey_path(survey)
            #buttons class="col"
              = link_to 'Edit', edit_survey_path(survey), class: 'btn btn-info'
              = link_to 'Destroy', survey, confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger' 
              = link_to 'Approve', approve_survey_path(survey), class: 'btn btn-primary' unless survey.approved?
              
              = link_to 'Finish', finish_survey_path(survey), confirm: 'This Survey will be finished and rewards will distribute. Are you sure?', class: 'btn btn-danger' unless survey.finished?
                   
              


  

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/edit_profile.html.slim
doctype html
html
  head
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
      = form_for (@profile), url: update_profile_survey_path(@survey) do |f|  
        = f.fields_for :profile do |ff|    
          = f.hidden_field :profilable_id
          div id="profile"
           = f.label "Country"
        br
        = f.country_select :country_code, priority: %w(US CA), prompt: 'Please select a country'
        br
        #field
          = f.label "City"
          br
          = render 'subregion_select', locals: {parent_region: f.object.country_code}
        br
        = f.label "Gender"
        br
        = f.select :gender, Profile.genders.keys.to_a
        br
        = f.label "Your Language"
        br
        = f.select :lang, Profile.langs.keys.to_a
        br
        #ages
          = f.label "Age ranges"          
          = f.number_field :min_age
          to 
          = f.number_field :max_age

        
        

        = f.submit 'Send', class: "btn btn-primary"

app/views/surveys/index.html.slim
  .container       
    # class="row"
        - @surveys.each do |survey|
          .col-md-4        
            # class="card mb-4 box-shadow"
             # class="card-header"
              - if current_user.id == survey.user_id
                h6 class="my-0 font-weight-normal" style="display: inline-block" =link_to survey.name, survey_path(survey)
              - else
                h6 class="my-0 font-weight-normal" style="display: inline-block" =link_to survey.name, new_response_survey_path(survey)
             # class="card-body"
              span class="badge badge-info" = "Reward: #{survey.reward} FBC / User"
              span class="badge badge-danger" = "Limit :#{survey.plimit} User"
              span class="badge badge-success" = "Total R. :#{survey.totalr} FBC"
              hr

              - if current_user.id == survey.user_id
                = link_to 'Edit', edit_survey_path(survey), class: 'btn btn-info btn-sm'
                = link_to 'Destroy', survey, confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger btn-sm'
                = link_to 'Finish', survey, confirm: 'Are you sure?', method: :finish, class: 'btn btn-danger btn-sm' if survey.approved?
              - else  
                - if current_user.admin?
                  = link_to 'Approve', survey, confirm: 'Are you sure?', method: :approve, class: 'btn btn-primary btn-sm' unless survey.approved?
                  = link_to 'Destroy', survey, confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger btn-sm'
                  = link_to 'Show', survey_path(survey), class: 'btn btn-info btn-sm'
                  = link_to 'Edit', edit_survey_path(survey), class: 'btn btn-info btn-sm'
                  = link_to 'Finish', finish_survey_path(survey), confirm: 'Are you sure?', class: 'btn btn-danger btn-sm' if survey.approved?
                - else
                  = link_to 'Participate Now', new_response_survey_path(survey), class: 'btn btn-info btn-sm'
                  
         
                    
                    
    

app/views/surveys/new.html.slim
#newsurvey class="container"
	h1 New Survey
	= render 'form', survey: @survey
	= link_to 'Back', surveys_path

app/views/surveys/new_profile.html.slim
doctype html
html
  head
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
      = form_for (@profile), url: create_profile_survey_path(@survey) do |f|  
        = f.fields_for :profile do |ff|    
          = f.hidden_field :profilable_id
          div id="profile"
           = f.label "Country"
        br
        = f.country_select :country_code, priority: %w(US CA), prompt: 'Please select a country'
        br
        #field
          = f.label "City"
          br
          = render 'subregion_select', locals: {parent_region: f.object.country_code}
        br
        = f.label "Gender"
        br
        = f.select :gender, Profile.genders.keys.to_a
        br
        = f.label "Your Language"
        br
        = f.select :lang, Profile.langs.keys.to_a
        br
        #ages
          = f.label "Age ranges"          
          = f.number_field :min_age
          to 
          = f.number_field :max_age
          

        
        

        = f.submit 'Send', class: "btn btn-primary"

app/views/surveys/new_response.html.slim
 .container
  h1 = @survey.name
  # class="card-deck mb-3 text-left"
    = form_for (@response), url: create_response_survey_path(@survey) do |f|
      # class="card mb-4"
        = f.fields_for :answers do |ff|
          br
          - q = ff.object.question
          # class="card-header"
            h2 = q.title
          = ff.hidden_field :question_id
          div id="question"
          - # add the radios for each options for the question
          - q.options.each do |option|    
            = label_tag do
            
              = ff.radio_button :option_id, option.id
              = "  #{option.otext}"

            
            

      = f.submit 'Send', class: "btn btn-primary"

app/views/surveys/review.html.slim
- if current_user.admin?
  h3 WAITING APPROVE AND REVIEW
  #container
    - @surveys.each do |survey|
      #survey class="row"
            #title class="col"       
              h6 style="display: inline-block" =link_to "#{survey.name} ( T.Reward:#{survey.tempreward}) and A.Reward:#{survey.reward}", new_response_survey_path(survey)
            #buttons class="col"
              = link_to 'Edit', edit_survey_path(survey), class: 'btn btn-info'
              = link_to 'Destroy', survey, confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger' 
              = link_to 'Approve', approve_survey_path(survey), class: 'btn btn-primary' unless survey.approved?
              
              = link_to 'Finish', finish_survey_path(survey), confirm: 'This Survey will be finished and rewards will distribute. Are you sure?', class: 'btn btn-danger' if survey.approved?
    
           

        


  #container
    h3 APPROVED AND WAITING FINISH LIMIT
    = render 'unfinished_surveys'

app/views/surveys/show.html.slim
.container
	h4 = @survey.name
	span class="badge badge-info" = " (Total responses: #{@survey.responses.size})"
	- @survey.questions.each do |question|
		# class="card-deck mb-3 text-left"
			# class="card mb-4"
				# class="card-header"
					= question.title
					
				# class="card-body"
					= pie_chart question.answers.joins(:option).group(:otext).count			
					- question.options.each do |option|
						.option	
							= option.otext
							span class="badge badge-info" = " #{option.answers.size}"

	- if current_user.admin?
		= link_to 'Approve', @survey, confirm: 'Are you sure?', method: :approve, class: 'btn btn-primary' unless @survey.approved?
		= link_to 'Edit Survey', edit_survey_path(@survey), style: 'center',  class: 'btn btn-primary' unless @survey.finished?
					
	- elsif current_user.id == @survey.user_id
		= link_to 'Edit Survey', edit_survey_path(@survey),  class: 'btn btn-primary' unless @survey.finished?	
- if @survey.profile != nil && (current_user.admin? or (current_user.id == @survey.user_id))
	# class="card-header"
		h6 Users Filtering Profile
	# class="card-body"
		span class="badge badge-info" = "Country: #{@country.name}"
		span class="badge badge-secondary" = "State:  #{@state.name}"
		span class="badge badge-warning" = "Gender:  #{@survey.profile.gender}"
		span class="badge badge-dark" = "Lang:  #{@survey.profile.lang}"
		span class="badge badge-danger" = "Max Age:  #{@survey.profile.max_age}"
		span class="badge badge-primary" = "Min Age:  #{@survey.profile.min_age}"
	= link_to 'Edit Survey Profile', edit_profile_survey_path(@survey), class: 'btn btn-info btn-sm' unless @survey.finished?	